name: S3 Deploy Workflow
on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy to AWS S3 and invalidate CloudFront cache
        uses: pukonu/action-deploy-webapp-aws@v.1.2.2
        id: deploy
        with:
          build_path: './build'
          bucket_name: ${{ secrets.S3_BUCKET }}
          bucket_key: ''
          distribution_invalidation_path: '/*'
          empty_bucket: 'false'
        env:
          DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
